<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>IoTDataCollection</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IoTDataCollection.Domain\IoTDataCollection.Domain.csproj" />
    <ProjectReference Include="..\IoTDataCollection.Application.Contracts\IoTDataCollection.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Account.Application" Version="8.3.1" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="8.3.1" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="8.3.1" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="8.3.1" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="8.3.1" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="8.3.1" />
    <PackageReference Include="MQTTnet" Version="4.3.1.873" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
